package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Citas generated by hbm2java
 */
public class Citas  implements java.io.Serializable {


     private int idExamen;
     private Examen examen;
     private Date fecha;
     private String hora;

    public Citas() {
    }

	
    public Citas(Examen examen) {
        this.examen = examen;
    }
    public Citas(Examen examen, Date fecha, String hora) {
       this.examen = examen;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public int getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(int idExamen) {
        this.idExamen = idExamen;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }




}


