package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1



/**
 * ExamenOrinaFq generated by hbm2java
 */
public class ExamenOrinaFq  implements java.io.Serializable {


     private int idExamenOrina;
     private ExamenOrina examenOrina;
     private String color;
     private String aspecto;
     private Integer densidad;
     private Integer ph;
     private Integer proteinas;
     private Integer glucosa;
     private Integer sangreOculta;
     private Integer cuerposCet;
     private Integer urobilinogeno;
     private Integer bilirrubina;
     private Integer nitritos;
     private Integer hemoglobina;
     private Integer esterasa;
     private String registro;

    public ExamenOrinaFq() {
    }

	
    public ExamenOrinaFq(ExamenOrina examenOrina) {
        this.examenOrina = examenOrina;
    }
    public ExamenOrinaFq(ExamenOrina examenOrina, String color, String aspecto, Integer densidad, Integer ph, Integer proteinas, Integer glucosa, Integer sangreOculta, Integer cuerposCet, Integer urobilinogeno, Integer bilirrubina, Integer nitritos, Integer hemoglobina, Integer esterasa, String registro) {
       this.examenOrina = examenOrina;
       this.color = color;
       this.aspecto = aspecto;
       this.densidad = densidad;
       this.ph = ph;
       this.proteinas = proteinas;
       this.glucosa = glucosa;
       this.sangreOculta = sangreOculta;
       this.cuerposCet = cuerposCet;
       this.urobilinogeno = urobilinogeno;
       this.bilirrubina = bilirrubina;
       this.nitritos = nitritos;
       this.hemoglobina = hemoglobina;
       this.esterasa = esterasa;
       this.registro = registro;
    }
   
    public int getIdExamenOrina() {
        return this.idExamenOrina;
    }
    
    public void setIdExamenOrina(int idExamenOrina) {
        this.idExamenOrina = idExamenOrina;
    }
    public ExamenOrina getExamenOrina() {
        return this.examenOrina;
    }
    
    public void setExamenOrina(ExamenOrina examenOrina) {
        this.examenOrina = examenOrina;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getAspecto() {
        return this.aspecto;
    }
    
    public void setAspecto(String aspecto) {
        this.aspecto = aspecto;
    }
    public Integer getDensidad() {
        return this.densidad;
    }
    
    public void setDensidad(Integer densidad) {
        this.densidad = densidad;
    }
    public Integer getPh() {
        return this.ph;
    }
    
    public void setPh(Integer ph) {
        this.ph = ph;
    }
    public Integer getProteinas() {
        return this.proteinas;
    }
    
    public void setProteinas(Integer proteinas) {
        this.proteinas = proteinas;
    }
    public Integer getGlucosa() {
        return this.glucosa;
    }
    
    public void setGlucosa(Integer glucosa) {
        this.glucosa = glucosa;
    }
    public Integer getSangreOculta() {
        return this.sangreOculta;
    }
    
    public void setSangreOculta(Integer sangreOculta) {
        this.sangreOculta = sangreOculta;
    }
    public Integer getCuerposCet() {
        return this.cuerposCet;
    }
    
    public void setCuerposCet(Integer cuerposCet) {
        this.cuerposCet = cuerposCet;
    }
    public Integer getUrobilinogeno() {
        return this.urobilinogeno;
    }
    
    public void setUrobilinogeno(Integer urobilinogeno) {
        this.urobilinogeno = urobilinogeno;
    }
    public Integer getBilirrubina() {
        return this.bilirrubina;
    }
    
    public void setBilirrubina(Integer bilirrubina) {
        this.bilirrubina = bilirrubina;
    }
    public Integer getNitritos() {
        return this.nitritos;
    }
    
    public void setNitritos(Integer nitritos) {
        this.nitritos = nitritos;
    }
    public Integer getHemoglobina() {
        return this.hemoglobina;
    }
    
    public void setHemoglobina(Integer hemoglobina) {
        this.hemoglobina = hemoglobina;
    }
    public Integer getEsterasa() {
        return this.esterasa;
    }
    
    public void setEsterasa(Integer esterasa) {
        this.esterasa = esterasa;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


