package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1



/**
 * ExamenHecesCp generated by hbm2java
 */
public class ExamenHecesCp  implements java.io.Serializable {


     private int idExamenHeces;
     private ExamenHeces examenHeces;
     private String entamoebaHA;
     private String entamoebaHQ;
     private String entamoebaColiA;
     private String entamoebaColiQ;
     private String endolimaxA;
     private String endolimaxQ;
     private String giardiaA;
     private String giardiaQ;
     private String trichomonasA;
     private String trichomonasQ;
     private String chilomastixA;
     private String chilomastixQ;
     private String iodamoebaA;
     private String iodamoebaQ;
     private String otrosA;
     private String otrosQ;
     private String registro;

    public ExamenHecesCp() {
    }

	
    public ExamenHecesCp(ExamenHeces examenHeces) {
        this.examenHeces = examenHeces;
    }
    public ExamenHecesCp(ExamenHeces examenHeces, String entamoebaHA, String entamoebaHQ, String entamoebaColiA, String entamoebaColiQ, String endolimaxA, String endolimaxQ, String giardiaA, String giardiaQ, String trichomonasA, String trichomonasQ, String chilomastixA, String chilomastixQ, String iodamoebaA, String iodamoebaQ, String otrosA, String otrosQ, String registro) {
       this.examenHeces = examenHeces;
       this.entamoebaHA = entamoebaHA;
       this.entamoebaHQ = entamoebaHQ;
       this.entamoebaColiA = entamoebaColiA;
       this.entamoebaColiQ = entamoebaColiQ;
       this.endolimaxA = endolimaxA;
       this.endolimaxQ = endolimaxQ;
       this.giardiaA = giardiaA;
       this.giardiaQ = giardiaQ;
       this.trichomonasA = trichomonasA;
       this.trichomonasQ = trichomonasQ;
       this.chilomastixA = chilomastixA;
       this.chilomastixQ = chilomastixQ;
       this.iodamoebaA = iodamoebaA;
       this.iodamoebaQ = iodamoebaQ;
       this.otrosA = otrosA;
       this.otrosQ = otrosQ;
       this.registro = registro;
    }
   
    public int getIdExamenHeces() {
        return this.idExamenHeces;
    }
    
    public void setIdExamenHeces(int idExamenHeces) {
        this.idExamenHeces = idExamenHeces;
    }
    public ExamenHeces getExamenHeces() {
        return this.examenHeces;
    }
    
    public void setExamenHeces(ExamenHeces examenHeces) {
        this.examenHeces = examenHeces;
    }
    public String getEntamoebaHA() {
        return this.entamoebaHA;
    }
    
    public void setEntamoebaHA(String entamoebaHA) {
        this.entamoebaHA = entamoebaHA;
    }
    public String getEntamoebaHQ() {
        return this.entamoebaHQ;
    }
    
    public void setEntamoebaHQ(String entamoebaHQ) {
        this.entamoebaHQ = entamoebaHQ;
    }
    public String getEntamoebaColiA() {
        return this.entamoebaColiA;
    }
    
    public void setEntamoebaColiA(String entamoebaColiA) {
        this.entamoebaColiA = entamoebaColiA;
    }
    public String getEntamoebaColiQ() {
        return this.entamoebaColiQ;
    }
    
    public void setEntamoebaColiQ(String entamoebaColiQ) {
        this.entamoebaColiQ = entamoebaColiQ;
    }
    public String getEndolimaxA() {
        return this.endolimaxA;
    }
    
    public void setEndolimaxA(String endolimaxA) {
        this.endolimaxA = endolimaxA;
    }
    public String getEndolimaxQ() {
        return this.endolimaxQ;
    }
    
    public void setEndolimaxQ(String endolimaxQ) {
        this.endolimaxQ = endolimaxQ;
    }
    public String getGiardiaA() {
        return this.giardiaA;
    }
    
    public void setGiardiaA(String giardiaA) {
        this.giardiaA = giardiaA;
    }
    public String getGiardiaQ() {
        return this.giardiaQ;
    }
    
    public void setGiardiaQ(String giardiaQ) {
        this.giardiaQ = giardiaQ;
    }
    public String getTrichomonasA() {
        return this.trichomonasA;
    }
    
    public void setTrichomonasA(String trichomonasA) {
        this.trichomonasA = trichomonasA;
    }
    public String getTrichomonasQ() {
        return this.trichomonasQ;
    }
    
    public void setTrichomonasQ(String trichomonasQ) {
        this.trichomonasQ = trichomonasQ;
    }
    public String getChilomastixA() {
        return this.chilomastixA;
    }
    
    public void setChilomastixA(String chilomastixA) {
        this.chilomastixA = chilomastixA;
    }
    public String getChilomastixQ() {
        return this.chilomastixQ;
    }
    
    public void setChilomastixQ(String chilomastixQ) {
        this.chilomastixQ = chilomastixQ;
    }
    public String getIodamoebaA() {
        return this.iodamoebaA;
    }
    
    public void setIodamoebaA(String iodamoebaA) {
        this.iodamoebaA = iodamoebaA;
    }
    public String getIodamoebaQ() {
        return this.iodamoebaQ;
    }
    
    public void setIodamoebaQ(String iodamoebaQ) {
        this.iodamoebaQ = iodamoebaQ;
    }
    public String getOtrosA() {
        return this.otrosA;
    }
    
    public void setOtrosA(String otrosA) {
        this.otrosA = otrosA;
    }
    public String getOtrosQ() {
        return this.otrosQ;
    }
    
    public void setOtrosQ(String otrosQ) {
        this.otrosQ = otrosQ;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


