package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1



/**
 * ExamenOrinaM generated by hbm2java
 */
public class ExamenOrinaM  implements java.io.Serializable {


     private int idExamenOrina;
     private ExamenOrina examenOrina;
     private Integer cilindros;
     private Integer granulosos;
     private Integer leucocitarios;
     private Integer hematicos;
     private Integer hialinos;
     private Integer hematies;
     private Integer leucocitos;
     private Integer celulasEpiteliales;
     private Integer cristales;
     private Integer parasitologico;
     private Integer otros;
     private String registro;

    public ExamenOrinaM() {
    }

	
    public ExamenOrinaM(ExamenOrina examenOrina) {
        this.examenOrina = examenOrina;
    }
    public ExamenOrinaM(ExamenOrina examenOrina, Integer cilindros, Integer granulosos, Integer leucocitarios, Integer hematicos, Integer hialinos, Integer hematies, Integer leucocitos, Integer celulasEpiteliales, Integer cristales, Integer parasitologico, Integer otros, String registro) {
       this.examenOrina = examenOrina;
       this.cilindros = cilindros;
       this.granulosos = granulosos;
       this.leucocitarios = leucocitarios;
       this.hematicos = hematicos;
       this.hialinos = hialinos;
       this.hematies = hematies;
       this.leucocitos = leucocitos;
       this.celulasEpiteliales = celulasEpiteliales;
       this.cristales = cristales;
       this.parasitologico = parasitologico;
       this.otros = otros;
       this.registro = registro;
    }
   
    public int getIdExamenOrina() {
        return this.idExamenOrina;
    }
    
    public void setIdExamenOrina(int idExamenOrina) {
        this.idExamenOrina = idExamenOrina;
    }
    public ExamenOrina getExamenOrina() {
        return this.examenOrina;
    }
    
    public void setExamenOrina(ExamenOrina examenOrina) {
        this.examenOrina = examenOrina;
    }
    public Integer getCilindros() {
        return this.cilindros;
    }
    
    public void setCilindros(Integer cilindros) {
        this.cilindros = cilindros;
    }
    public Integer getGranulosos() {
        return this.granulosos;
    }
    
    public void setGranulosos(Integer granulosos) {
        this.granulosos = granulosos;
    }
    public Integer getLeucocitarios() {
        return this.leucocitarios;
    }
    
    public void setLeucocitarios(Integer leucocitarios) {
        this.leucocitarios = leucocitarios;
    }
    public Integer getHematicos() {
        return this.hematicos;
    }
    
    public void setHematicos(Integer hematicos) {
        this.hematicos = hematicos;
    }
    public Integer getHialinos() {
        return this.hialinos;
    }
    
    public void setHialinos(Integer hialinos) {
        this.hialinos = hialinos;
    }
    public Integer getHematies() {
        return this.hematies;
    }
    
    public void setHematies(Integer hematies) {
        this.hematies = hematies;
    }
    public Integer getLeucocitos() {
        return this.leucocitos;
    }
    
    public void setLeucocitos(Integer leucocitos) {
        this.leucocitos = leucocitos;
    }
    public Integer getCelulasEpiteliales() {
        return this.celulasEpiteliales;
    }
    
    public void setCelulasEpiteliales(Integer celulasEpiteliales) {
        this.celulasEpiteliales = celulasEpiteliales;
    }
    public Integer getCristales() {
        return this.cristales;
    }
    
    public void setCristales(Integer cristales) {
        this.cristales = cristales;
    }
    public Integer getParasitologico() {
        return this.parasitologico;
    }
    
    public void setParasitologico(Integer parasitologico) {
        this.parasitologico = parasitologico;
    }
    public Integer getOtros() {
        return this.otros;
    }
    
    public void setOtros(Integer otros) {
        this.otros = otros;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }




}


