package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1



/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private Integer idExamen;
     private Medicos medicos;
     private Pacientes pacientes;
     private String categoria;
     private String examenTipo;
     private String estado;
     private String registro;
     private ExamenesVarios examenesVarios;
     private ExamenOrina examenOrina;
     private ExamenEmbarazo examenEmbarazo;
     private Citas citas;
     private ExamenHeces examenHeces;

    public Examen() {
    }

    public Examen(Medicos medicos, Pacientes pacientes, String categoria, String examenTipo, String estado, String registro, ExamenesVarios examenesVarios, ExamenOrina examenOrina, ExamenEmbarazo examenEmbarazo, Citas citas, ExamenHeces examenHeces) {
       this.medicos = medicos;
       this.pacientes = pacientes;
       this.categoria = categoria;
       this.examenTipo = examenTipo;
       this.estado = estado;
       this.registro = registro;
       this.examenesVarios = examenesVarios;
       this.examenOrina = examenOrina;
       this.examenEmbarazo = examenEmbarazo;
       this.citas = citas;
       this.examenHeces = examenHeces;
    }
   
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public Pacientes getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Pacientes pacientes) {
        this.pacientes = pacientes;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getExamenTipo() {
        return this.examenTipo;
    }
    
    public void setExamenTipo(String examenTipo) {
        this.examenTipo = examenTipo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public ExamenesVarios getExamenesVarios() {
        return this.examenesVarios;
    }
    
    public void setExamenesVarios(ExamenesVarios examenesVarios) {
        this.examenesVarios = examenesVarios;
    }
    public ExamenOrina getExamenOrina() {
        return this.examenOrina;
    }
    
    public void setExamenOrina(ExamenOrina examenOrina) {
        this.examenOrina = examenOrina;
    }
    public ExamenEmbarazo getExamenEmbarazo() {
        return this.examenEmbarazo;
    }
    
    public void setExamenEmbarazo(ExamenEmbarazo examenEmbarazo) {
        this.examenEmbarazo = examenEmbarazo;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public ExamenHeces getExamenHeces() {
        return this.examenHeces;
    }
    
    public void setExamenHeces(ExamenHeces examenHeces) {
        this.examenHeces = examenHeces;
    }




}


