package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1



/**
 * Kardex generated by hbm2java
 */
public class Kardex  implements java.io.Serializable {


     private Integer idMes;
     private Integer ia1;
     private Integer ia2;
     private Integer ca1;
     private Integer ca2;
     private Integer ea1;
     private Integer ea2;
     private Integer ea1r;
     private Integer ea1nr;
     private Integer ea2r;
     private Integer ea2nr;
     private Integer pa1r;
     private Integer pa1nr;
     private Integer pa2r;
     private Integer pa2nr;
     private Integer ta1r;
     private Integer ta1nr;
     private Integer ta2r;
     private Integer ta2nr;
     private Integer xa1r;
     private Integer xa1nr;
     private Integer xa2r;
     private Integer xa2nr;
     private Integer cca1;
     private Integer cca2;
     private Integer npa1;
     private Integer npa2;
     private String mes;

    public Kardex() {
    }

    public Kardex(Integer ia1, Integer ia2, Integer ca1, Integer ca2, Integer ea1, Integer ea2, Integer ea1r, Integer ea1nr, Integer ea2r, Integer ea2nr, Integer pa1r, Integer pa1nr, Integer pa2r, Integer pa2nr, Integer ta1r, Integer ta1nr, Integer ta2r, Integer ta2nr, Integer xa1r, Integer xa1nr, Integer xa2r, Integer xa2nr, Integer cca1, Integer cca2, Integer npa1, Integer npa2, String mes) {
       this.ia1 = ia1;
       this.ia2 = ia2;
       this.ca1 = ca1;
       this.ca2 = ca2;
       this.ea1 = ea1;
       this.ea2 = ea2;
       this.ea1r = ea1r;
       this.ea1nr = ea1nr;
       this.ea2r = ea2r;
       this.ea2nr = ea2nr;
       this.pa1r = pa1r;
       this.pa1nr = pa1nr;
       this.pa2r = pa2r;
       this.pa2nr = pa2nr;
       this.ta1r = ta1r;
       this.ta1nr = ta1nr;
       this.ta2r = ta2r;
       this.ta2nr = ta2nr;
       this.xa1r = xa1r;
       this.xa1nr = xa1nr;
       this.xa2r = xa2r;
       this.xa2nr = xa2nr;
       this.cca1 = cca1;
       this.cca2 = cca2;
       this.npa1 = npa1;
       this.npa2 = npa2;
       this.mes = mes;
    }
   
    public Integer getIdMes() {
        return this.idMes;
    }
    
    public void setIdMes(Integer idMes) {
        this.idMes = idMes;
    }
    public Integer getIa1() {
        return this.ia1;
    }
    
    public void setIa1(Integer ia1) {
        this.ia1 = ia1;
    }
    public Integer getIa2() {
        return this.ia2;
    }
    
    public void setIa2(Integer ia2) {
        this.ia2 = ia2;
    }
    public Integer getCa1() {
        return this.ca1;
    }
    
    public void setCa1(Integer ca1) {
        this.ca1 = ca1;
    }
    public Integer getCa2() {
        return this.ca2;
    }
    
    public void setCa2(Integer ca2) {
        this.ca2 = ca2;
    }
    public Integer getEa1() {
        return this.ea1;
    }
    
    public void setEa1(Integer ea1) {
        this.ea1 = ea1;
    }
    public Integer getEa2() {
        return this.ea2;
    }
    
    public void setEa2(Integer ea2) {
        this.ea2 = ea2;
    }
    public Integer getEa1r() {
        return this.ea1r;
    }
    
    public void setEa1r(Integer ea1r) {
        this.ea1r = ea1r;
    }
    public Integer getEa1nr() {
        return this.ea1nr;
    }
    
    public void setEa1nr(Integer ea1nr) {
        this.ea1nr = ea1nr;
    }
    public Integer getEa2r() {
        return this.ea2r;
    }
    
    public void setEa2r(Integer ea2r) {
        this.ea2r = ea2r;
    }
    public Integer getEa2nr() {
        return this.ea2nr;
    }
    
    public void setEa2nr(Integer ea2nr) {
        this.ea2nr = ea2nr;
    }
    public Integer getPa1r() {
        return this.pa1r;
    }
    
    public void setPa1r(Integer pa1r) {
        this.pa1r = pa1r;
    }
    public Integer getPa1nr() {
        return this.pa1nr;
    }
    
    public void setPa1nr(Integer pa1nr) {
        this.pa1nr = pa1nr;
    }
    public Integer getPa2r() {
        return this.pa2r;
    }
    
    public void setPa2r(Integer pa2r) {
        this.pa2r = pa2r;
    }
    public Integer getPa2nr() {
        return this.pa2nr;
    }
    
    public void setPa2nr(Integer pa2nr) {
        this.pa2nr = pa2nr;
    }
    public Integer getTa1r() {
        return this.ta1r;
    }
    
    public void setTa1r(Integer ta1r) {
        this.ta1r = ta1r;
    }
    public Integer getTa1nr() {
        return this.ta1nr;
    }
    
    public void setTa1nr(Integer ta1nr) {
        this.ta1nr = ta1nr;
    }
    public Integer getTa2r() {
        return this.ta2r;
    }
    
    public void setTa2r(Integer ta2r) {
        this.ta2r = ta2r;
    }
    public Integer getTa2nr() {
        return this.ta2nr;
    }
    
    public void setTa2nr(Integer ta2nr) {
        this.ta2nr = ta2nr;
    }
    public Integer getXa1r() {
        return this.xa1r;
    }
    
    public void setXa1r(Integer xa1r) {
        this.xa1r = xa1r;
    }
    public Integer getXa1nr() {
        return this.xa1nr;
    }
    
    public void setXa1nr(Integer xa1nr) {
        this.xa1nr = xa1nr;
    }
    public Integer getXa2r() {
        return this.xa2r;
    }
    
    public void setXa2r(Integer xa2r) {
        this.xa2r = xa2r;
    }
    public Integer getXa2nr() {
        return this.xa2nr;
    }
    
    public void setXa2nr(Integer xa2nr) {
        this.xa2nr = xa2nr;
    }
    public Integer getCca1() {
        return this.cca1;
    }
    
    public void setCca1(Integer cca1) {
        this.cca1 = cca1;
    }
    public Integer getCca2() {
        return this.cca2;
    }
    
    public void setCca2(Integer cca2) {
        this.cca2 = cca2;
    }
    public Integer getNpa1() {
        return this.npa1;
    }
    
    public void setNpa1(Integer npa1) {
        this.npa1 = npa1;
    }
    public Integer getNpa2() {
        return this.npa2;
    }
    
    public void setNpa2(Integer npa2) {
        this.npa2 = npa2;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }




}


