package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medicos generated by hbm2java
 */
public class Medicos  implements java.io.Serializable {


     private Integer idMedico;
     private String nombre;
     private String apellido;
     private String cargo;
     private String noCedula;
     private Integer telefono;
     private Integer edad;
     private String direccion;
     private byte[] foto;
     private String registro;
     private Set examens = new HashSet(0);
     private Roles roles;
     private Usuario usuario;

    public Medicos() {
    }

    public Medicos(String nombre, String apellido, String cargo, String noCedula, Integer telefono, Integer edad, String direccion, byte[] foto, String registro, Set examens, Roles roles, Usuario usuario) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cargo = cargo;
       this.noCedula = noCedula;
       this.telefono = telefono;
       this.edad = edad;
       this.direccion = direccion;
       this.foto = foto;
       this.registro = registro;
       this.examens = examens;
       this.roles = roles;
       this.usuario = usuario;
    }
   
    public Integer getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(Integer idMedico) {
        this.idMedico = idMedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getNoCedula() {
        return this.noCedula;
    }
    
    public void setNoCedula(String noCedula) {
        this.noCedula = noCedula;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


