package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pacientes generated by hbm2java
 */
public class Pacientes  implements java.io.Serializable {


     private Integer idPaciente;
     private String nombres;
     private String apellidos;
     private Integer noExpediente;
     private String sexo;
     private String sala;
     private Integer telefono;
     private Integer edad;
     private String noCedula;
     private String tipoSangre;
     private String departamento;
     private String direccion;
     private String registro;
     private Set examens = new HashSet(0);

    public Pacientes() {
    }

	
    public Pacientes(String registro) {
        this.registro = registro;
    }
    public Pacientes(String nombres, String apellidos, Integer noExpediente, String sexo, String sala, Integer telefono, Integer edad, String noCedula, String tipoSangre, String departamento, String direccion, String registro, Set examens) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.noExpediente = noExpediente;
       this.sexo = sexo;
       this.sala = sala;
       this.telefono = telefono;
       this.edad = edad;
       this.noCedula = noCedula;
       this.tipoSangre = tipoSangre;
       this.departamento = departamento;
       this.direccion = direccion;
       this.registro = registro;
       this.examens = examens;
    }
   
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getNoExpediente() {
        return this.noExpediente;
    }
    
    public void setNoExpediente(Integer noExpediente) {
        this.noExpediente = noExpediente;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getSala() {
        return this.sala;
    }
    
    public void setSala(String sala) {
        this.sala = sala;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getNoCedula() {
        return this.noCedula;
    }
    
    public void setNoCedula(String noCedula) {
        this.noCedula = noCedula;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


