package POJO;
// Generated 02-17-2017 07:23:49 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Medicos medicos;
     private String nombre;
     private String registro;
     private byte[] password;

    public Usuario() {
    }

	
    public Usuario(Medicos medicos) {
        this.medicos = medicos;
    }
    public Usuario(Medicos medicos, String nombre, String registro, byte[] password) {
       this.medicos = medicos;
       this.nombre = nombre;
       this.registro = registro;
       this.password = password;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }




}


